### ISSUE TITLE
Image View Builder Does Not Use `media.supports`

### ISSUE THREAD

**Issue by johnhowes** [lynx-json/jsua-lynx#46]
I tried to use a multi-source, scaled image like this:

```yaml
">image":
  scale: 1
  src: ./baseline_home_white_24pt_1x.png
  width: 24
  height: 24
  sources:
    - scale: 2
      src: ./baseline_home_white_24pt_2x.png
      width: 24
      height: 24
    - scale: 3
      src: ./baseline_home_white_24pt_3x.png
      width: 24
      height: 24
```

If I change the hint to `content`, the 2x image is selected based on the devicePixelRatio of my device. But with an `image` hint, we defer to the browser with the default `src` before ever checking sources.
